class_name Bullet extends Area2D
var speed = 700

signal bulletDamageSignal(body, bullet)

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.func setSpeed(value):
	
func setSpeed(value):
	speed = value
	
# Called every frame. 'delta' is the elapsed time since the previous frame.
func _physics_process(delta: float) -> void:
	position += transform.x * speed * delta

func _on_area_entered(area: Area2D) -> void:
	print("bullet is hitting area")
	if area is Slime:
		bulletDamageSignal.emit(area, self)
		
